name: Testing

on: [push, pull_request]

jobs:
  build:
    strategy:
      max-parallel: 20
      matrix:
        os: [ubuntu-latest] #, macos-latest]
        python-version: ["3.9", "3.10"]

    runs-on: ${{ matrix.os }}
    env:
      PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: "python"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/requirements.txt'
      - name: Install dependencies
        run: |
          pip install --quiet -r requirements.txt -r requirements-ci.txt
          pip install -e .
      - name: pytest
        run: |
          pytest --cov=matgl tests --color=yes
      - name: Coveralls
        uses: coverallsapp/github-action@v2
